# Generated by Django 5.1 on 2024-11-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
