# Generated by Django 5.1 on 2024-11-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_user_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
