# Generated by Django 5.1 on 2024-11-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_email_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='cc',
            field=models.BooleanField(default=False),
        ),
    ]
