# Generated by Django 5.1 on 2024-11-20 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_email_cc'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='bcc',
            field=models.ManyToManyField(related_name='emails_received_bcc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='email',
            name='cc',
        ),
        migrations.AddField(
            model_name='email',
            name='cc',
            field=models.ManyToManyField(related_name='emails_received_cc', to=settings.AUTH_USER_MODEL),
        ),
    ]
