# Generated by Django 5.1 on 2024-12-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_scheduledemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledemail',
            name='user',
        ),
    ]
