# Generated by Django 5.1 on 2024-12-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0012_remove_scheduledemail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
